### ISSUE TITLE
Provide more information when trying to use the plugin without proper system setup

### ISSUE THREAD

**Issue by tschneidereit** [fermyon/otel-plugin#11]
When I try running `spin otel setup`, I get the error `the docker daemon appears not to be running, so please start the daemon and try again`. It'd be great if instead we could show some more information about how to configure things, because I have no idea how to go from that state to having things work :)

**Comment by calebschoepp** [comment]
Great feedback. Thank you @tschneidereit!

**Comment by asteurer** [comment]
@tschneidereit What do you think about this? `The Docker daemon appears not to be running. The command to start Docker depends on your operating system. For instructions, check the correct page under https://docs.docker.com/engine/install/`

**Comment by calebschoepp** [comment]
Closed by #13
