### ISSUE TITLE
Make sure basic subcommands of `spin otel` always work

### ISSUE THREAD

**Issue by tschneidereit** [fermyon/otel-plugin#12]
Right now, not even `spin otel up -- --help` works without Docker running. I assume there's a check for some system setup things very early in the plugin's startup phase, and would hope that can be moved a bit later.

**Comment by asteurer** [comment]
Working on this

**Comment by asteurer** [comment]
See https://github.com/fermyon/otel-plugin/pull/13

**Comment by calebschoepp** [comment]
Closed by #13
