### ISSUE TITLE
Should `spin otel cleanup` actually clean up?

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/otel-plugin#18]
With the current implementation, `spin otel cleanup` **stops** but **does not remove** containers, that were spawned using `spin otel setup`. Given the name `cleanup` I would assume the underlying containers to be removed from my docker context instead of "just" being stopped.

I have two different approaches in mind, how we could address this:

## Option 1

Add an `--rm` flag to the `spin otel cleanup` command. If specified, we execute `docker rm -f <CONTAINER_ID>` instead of `docker stop <CONTAINER_IDS>`

## Option 2

Add a `spin otel stop` command (which will execute `docker stop <CONTAINER_IDS>`)
Change the implementation of `spin otel cleanup` to execute `docker rm -f <CONTAINER_IDS>`

**Comment by ThorstenHans** [comment]
@calebschoepp @asteurer @mikkelhegn any preferences?

**Comment by asteurer** [comment]
I'm a fan of <ins>**Option 1**</ins>. This way the user could benefit from a faster `spin otel up`, while still having the choice to remove the images.

**Comment by calebschoepp** [comment]
I like option 1 too.
